modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"

[[mods]]
modId="mdf"
version="0.0.1"
displayName="MigaMi's Devil Fruits"
authors="MigaMi"
credits="MrCrayfish"
description="Devil Fruits have arrived!"

[[dependencies.mdf]]
    modId="forge"
    mandatory=true
    versionRange="[44.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mdf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mdf]]
    modId="framework"
    mandatory=true
    versionRange="[0.6.16,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mdf]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.2,)"
    ordering="NONE"
    side="BOTH"